server {
    listen 80;
    server_name bachlex.id.vn;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name bachlex.id.vn;

    ssl_certificate /app/v3/ssl/fullchain.pem;
    ssl_certificate_key /app/v3/ssl/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Error handling
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
